version: '2.4'
services:
  MixerDB:
    container_name: MixerDB
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_DB=mixer
      - POSTGRES_USER=mixeruser
      - POSTGRES_PASSWORD=mixerpassword
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mixeruser -d mixer"]
      interval: 10s
      timeout: 5s
      retries: 1
  MixerBackend:
    container_name: MixerBackend
    image: mixeway/backend:0.9
    env_file:
      - environments
    ports:
      - 8443:8443
    volumes:
      - ./pki/:/etc/pki
    depends_on:
      MixerDB:
        condition: service_healthy
  MixerFrontend:
    container_name: MixerFrontend
    image: mixeway/frontend:0.9
    volumes:
      - ./pki/:/etc/pki
    ports:
      - 443:443
    depends_on:
      - MixerBackend
volumes:
  pgdata:

